apiVersion: v1
kind: Service
metadata:
  name: consumer-metrics
  namespace: streammetrics
  labels:
    app: consumer
spec:
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: consumer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-monitor
  namespace: streammetrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: consumer
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s