apiVersion: v1
kind: Service
metadata:
  name: streams-metrics
  namespace: streammetrics
  labels:
    app: streams
spec:
  ports:
    - name: metrics
      port: 8082
      targetPort: 8082
  selector:
    app: streams
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streams-monitor
  namespace: streammetrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: streams
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s